apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: classes.hwchiu.io
spec:
  group: hwchiu.io
  scope: Cluster
  names:
    plural: classes
    singular: class
    kind: Class
    shortNames:
    - c
  versions:
  - name: v1alpha1  # you can serve multiple versions e.g v1beta2 or v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              classMode:
                type: string
              number:
                type: integer
    additionalPrinterColumns:
    - name: Mode
      type: string
      description: Online or in-person
      jsonPath: .spec.classMode
    - name: Number
      type: integer
      description: Total number of people who attend the class
      jsonPath: .spec.number
