apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-never
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu-server
          image: ubuntu:22.04
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              protocol: "TCP"
