apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-ifnotpresent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu-server
          image: ubuntu:22.04
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: "TCP"
