apiVersion: v1
kind: Pod
metadata:
  name: signal1
spec:
  containers:
    - name: debug
      image: hwchiu/netutils
---
apiVersion: v1
kind: Pod
metadata:
  name: signal2
spec:
  containers:
    - name: debug
      image: ubuntu
      command: ['sh', '-c', 'sleep 9000s']
