apiVersion: apps/v1
kind: Deployment
metadata:
  name: prome-app-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prome-app
  template:
    metadata:
      labels:
        app: prome-app
    spec:
      containers:
        - name: server-1
          image: localbuild/python-example:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: prome-app
  labels:
    app: prome-app
spec:
  selector:
    app: prome-app
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  type: ClusterIP
