apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-noconfig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-noconfig
  template:
    metadata:
      labels:
        app: argo-noconfig
    spec:
      containers:
        - name: argo-noconfig-server
          image: hwchiu/python-example
          ports:
            - containerPort: 5000
              protocol: "TCP"
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: config-demo
                  key: LOG_LEVEL
          volumeMounts:
          - name: config
            mountPath: "/config"
      volumes:
        - name: config
          configMap:
            name: config-demo2     
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-demo
data:
  # property-like keys; each key maps to a simple value
  USE_REDIS: "False"
  LOG_LEVEL: "DEBUG"

  # file-like keys
  config.yml: |
    USER_REDIS: "True"
    REDIS_HOST: "redis2"
