apiVersion: apps/v1
kind: Deployment
metadata:
  name: format-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: format
  template:
    metadata:
      labels:
        app: format
    spec:
      containers:
        - name: server-1
          image: hwchiu/netutils:python
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "128m"              
        - name: server-2
          image: hwchiu/netutils:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "128m" 
        - name: butybox
          image: busybox:latest
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
          ports:
            - containerPort: 5000
              protocol: "TCP"
---

