apiVersion: apps/v1
kind: Deployment
metadata:
  name: localbuild-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localbuild
  template:
    metadata:
      labels:
        app: localbuild
    spec:
      containers:
        - name: server-1
          image: localbuild/python-example:latest
          imagePullPolicy: Never
