apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: vpa-1
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: vpa-1
  updatePolicy:
    updateMode: "Off"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-1
spec:
  selector:
    matchLabels:
      app: vpa-1
  replicas: 1
  template:
    metadata:
      labels:
        app: vpa-1
    spec:
      containers:
        - name: vpa-1
          image: hwchiu/netutils
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 250Mi
          command: ["/bin/sh"]
          args:
            - "-c"
            - "while true; do timeout 0.5s yes >/dev/null; sleep 0.5s; done"
