apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-2
  namespace: argocd
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - my_values.yaml
    path: nginx
    repoURL: http://gitea-http.gitea:3000/hwchiu/k8s-app
    targetRevision: HEAD
  syncPolicy:
    automated: {}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: official-app
  namespace: argocd
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
  syncPolicy:
    automated: {}
